server:
  port: 8001

spring:
  application:
    name: product-service
  profiles:
    active: local

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
